version: '3'
services:
  nestjs-demo:
    image: nestjs-demo
    build:
      context: .
    command: npm run start:dev
    volumes:
      - ./:/app
    ports:
      - 9001:9001
    links:
      - nestjs-demo-database
    depends_on:
      - nestjs-demo-database
    environment:
      DB_NAME: things
      DB_USER: admin_user
      DB_PASSWORD: s7aSm5xEjF7E37ABp3he
      DB_HOST: nestjs-demo-database
  nestjs-demo-database:
    image: postgres:12
    container_name: nestjs-demo-database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: things
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: s7aSm5xEjF7E37ABp3he
